name: Check Code Formatting ğŸ› ï¸
on:
  workflow_call:
jobs:
  cmake-format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: cmake-format check ğŸ›ï¸
        id: cmake-format
        uses: ./.github/actions/run-cmake-format
        with:
          failCondition: error
